# Generated by Django 3.2.6 on 2021-08-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Angularapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='PhotoFileName',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
