# Generated by Django 3.2.6 on 2021-08-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Angularapp', '0002_alter_employees_photofilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='PhotoFileName',
            field=models.CharField(max_length=100),
        ),
    ]
